<!-- latest jquery-->
<script src="{{ asset('') }}assets/js/jquery.min.js"></script><!-- Bootstrap js-->
<script src="{{ asset('') }}assets/js/bootstrap/bootstrap.bundle.min.js"></script><!-- feather icon js-->
<script src="{{ asset('') }}assets/js/icons/feather-icon/feather.min.js"></script>
<script src="{{ asset('') }}assets/js/icons/feather-icon/feather-icon.js"></script><!-- scrollbar js-->
<script src="{{ asset('') }}assets/js/scrollbar/simplebar.min.js"></script>
<script src="{{ asset('') }}assets/js/scrollbar/custom.js"></script><!-- Sidebar jquery-->
<script src="{{ asset('') }}assets/js/config.js"></script><!-- Plugins JS start-->
<script src="{{ asset('') }}assets/js/sidebar-menu.js"></script>
<script src="{{ asset('') }}assets/js/sidebar-pin.js"></script>
<script src="{{ asset('') }}assets/js/clock.js"></script>
<script src="{{ asset('') }}assets/js/slick/slick.min.js"></script>
<script src="{{ asset('') }}assets/js/slick/slick.js"></script>
<script src="{{ asset('') }}assets/js/header-slick.js"></script>
<script src="{{ asset('') }}assets/js/chart/apex-chart/apex-chart.js"></script>
<script src="{{ asset('') }}assets/js/chart/apex-chart/stock-prices.js"></script>
<script src="{{ asset('') }}assets/js/counter/counter-custom.js"></script>
<script src="{{ asset('') }}assets/js/notify/bootstrap-notify.min.js"></script>
<script src="{{ asset('') }}assets/js/dashboard/default.js"></script>
<script src="{{ asset('') }}assets/js/notify/index.js"></script>
<script src="{{ asset('') }}assets/js/datatable/datatables/jquery.dataTables.min.js"></script>
<script src="{{ asset('') }}assets/js/datatable/datatables/dataTables.js"></script>
<script src="{{ asset('') }}assets/js/datatable/datatables/dataTables.select.js"></script>
<script src="{{ asset('') }}assets/js/datatable/datatables/select.bootstrap5.js"></script>
<script src="{{ asset('') }}assets/js/typeahead/handlebars.js"></script>
<script src="{{ asset('') }}assets/js/typeahead/typeahead.bundle.js"></script>
<script src="{{ asset('') }}assets/js/typeahead/typeahead.custom.js"></script>
<script src="{{ asset('') }}assets/js/typeahead-search/handlebars.js"></script>
<script src="{{ asset('') }}assets/js/typeahead-search/typeahead-custom.js"></script><!-- Plugins JS Ends--><!-- Theme js-->
<script src="{{ asset('') }}assets/js/script.js"></script>
<script src="{{ asset('') }}assets/js/script1.js"></script>
<script src="{{ asset('') }}assets/js/datatable/datatables/datatable.custom.js"></script>
<script src="{{ asset('') }}assets/js/theme-customizer/customizer.js"></script>
<script src="{{ asset('') }}assets/js/datatable/datatables/dataTables1.js"></script>
<script src="{{ asset('') }}assets/js/datatable/datatables/dataTables.bootstrap5.js"></script>
<script src="{{ asset('') }}assets/js/datatable/datatables/datatable.custom2.js"></script>
<script src="{{ asset('') }}assets/js/sweet-alert/sweetalert.min.js"></script>
<script src="{{ asset('') }}assets/js/sweet-alert/app.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
